sbx_shotgun_unifrac:
  threads: 8
  wolr_fp: '/mnt/isilon/microbiome/analysis/biodata/shotgun_unifrac_database/bowtie2/'
  tree_fp: '/mnt/isilon/microbiome/analysis/biodata/shotgun_unifrac_database/qiime2_from_wfl/phylogeny.qza'
  woltka_map_fp: '/mnt/isilon/microbiome/analysis/biodata/shotgun_unifrac_database/'